language: java
sudo: false
jdk:
  openjdk7
  openjdk8
  openjdk9
  openjdk10
  openjdk11

jobs:
  include:
    - stage:
      name: Jar Build
      jdk: openjdk7
      script:
        - |
          if [[ "$TRAVIS_BRANCH" == "master" && -n "$TRAVIS_TAG" ]]; then
            ./build.sh "$TRAVIS_TAG"
          else
            ./build.sh
          fi
    - stage:
      name: JDK7 Tests
      jdk: openjdk7
      script: ./test.sh
    - stage:
      name: JDK8 Tests
      jdk: openjdk8
      script: ./test.sh
    - stage:
      name: JDK9 Tests
      jdk: openjdk9
      script: ./test.sh
    - stage:
      name: JDK10 Tests
      jdk: openjdk10
      script: ./test.sh
    - stage:
      name: JDK11 Tests
      jdk: openjdk11
      script: ./test.sh

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: ./target/verify*.jar
  skip_cleanup: true
  on:
    tags: true
