language: java
sudo: false
jdk:
  openjdk8
  openjdk9
  openjdk10
  openjdk11
  openjdk12

jobs:
  include:
    - stage:
      name: JDK8 Tests
      jdk: openjdk8
      before_script: ./build.sh
      script: ./test.sh
    - stage:
      name: JDK9 Tests
      jdk: openjdk9
      before_script: ./build.sh
      script: ./test.sh
    - stage:
      name: JDK10 Tests
      jdk: openjdk10
      before_script: ./build.sh
      script: ./test.sh
    - stage:
      name: JDK11 Tests
      jdk: openjdk11
      before_script: ./build.sh
      script: ./test.sh
    - stage:
      name: JDK12 Tests
      jdk: openjdk12
      before_script: ./build.sh
      script: ./test.sh

before_deploy: ./build.sh
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: ./target/verify*.jar
  skip_cleanup: true
  on:
    tags: true
